# Generated by Django 5.1.6 on 2025-09-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FundingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker', models.CharField(default='coinex', max_length=100)),
                ('market', models.CharField(max_length=100)),
                ('mark_price', models.FloatField()),
                ('latest_funding_rate', models.FloatField()),
                ('next_funding_rate', models.FloatField()),
                ('max_funding_rate', models.FloatField()),
                ('min_funding_rate', models.FloatField()),
                ('latest_funding_time', models.DateTimeField()),
                ('next_funding_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
