# Generated by Django 5.1.6 on 2025-09-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundingrate',
            name='latest_funding_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fundingrate',
            name='next_funding_time',
            field=models.IntegerField(),
        ),
    ]
