# Generated by Django 5.1.6 on 2025-09-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_fundingrate_latest_funding_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker', models.CharField(default='coinex', max_length=100)),
                ('market', models.CharField(max_length=100)),
                ('is_market_available', models.BooleanField(default=True)),
                ('maker_fee_rate', models.FloatField()),
                ('taker_fee_rate', models.FloatField()),
                ('min_amount', models.FloatField()),
            ],
        ),
    ]
