# Generated by Django 5.1.6 on 2025-09-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_marketstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketTicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker', models.CharField(default='coinex', max_length=100)),
                ('market', models.CharField(max_length=100)),
                ('close', models.FloatField()),
                ('high', models.FloatField()),
                ('index_price', models.FloatField()),
                ('last', models.FloatField()),
                ('low', models.FloatField()),
                ('mark_price', models.FloatField()),
                ('open', models.FloatField()),
                ('period', models.IntegerField()),
                ('value', models.BigIntegerField()),
                ('volume', models.FloatField()),
            ],
        ),
    ]
