# Generated by Django 5.1.6 on 2025-09-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_marketticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketticker',
            name='period',
            field=models.IntegerField(default=86400),
        ),
        migrations.AlterField(
            model_name='marketticker',
            name='value',
            field=models.FloatField(),
        ),
    ]
