# Generated by Django 5.1.6 on 2025-09-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_marketstatus_create_at_marketticker_create_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalizeDepth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker', models.CharField(default='coinex', max_length=100)),
                ('market', models.CharField(max_length=100)),
                ('support', models.FloatField()),
                ('resistance', models.FloatField()),
                ('buy_price', models.FloatField()),
                ('buy_stop_loss', models.FloatField()),
                ('sell_price', models.FloatField()),
                ('sell_stop_loss', models.FloatField()),
                ('buy_target', models.FloatField()),
                ('sell_target', models.FloatField()),
                ('last_price', models.FloatField()),
                ('fee', models.FloatField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
