# Generated by Django 5.1.6 on 2025-09-05 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_analizedepth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analizedepth',
            old_name='resistance',
            new_name='resistance_main',
        ),
        migrations.RenameField(
            model_name='analizedepth',
            old_name='support',
            new_name='support_main',
        ),
    ]
