# Generated by Django 5.1.6 on 2025-09-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_rename_resistance_analizedepth_resistance_main_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analizedepth',
            name='resistance_seccend',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analizedepth',
            name='support_seccend',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
