# Generated by Django 5.1.6 on 2025-09-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_analizedepth_resistance_seccend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analizedepth',
            name='min_buy_target',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analizedepth',
            name='min_sell_target',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analizedepth',
            name='open_buy',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analizedepth',
            name='open_sell',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
