# Generated by Django 5.1.6 on 2025-09-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_analizedepth_min_buy_target_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analizedepth',
            options={'ordering': ('-create_at',), 'verbose_name': 'تحلیل عمق بازار', 'verbose_name_plural': 'تحلیل\u200cهای عمق بازار'},
        ),
        migrations.RemoveField(
            model_name='analizedepth',
            name='resistance_seccend',
        ),
        migrations.RemoveField(
            model_name='analizedepth',
            name='support_seccend',
        ),
        migrations.AddField(
            model_name='analizedepth',
            name='resistance_second',
            field=models.FloatField(default=0, verbose_name='مقاومت دوم'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analizedepth',
            name='support_second',
            field=models.FloatField(default=0, verbose_name='حمایت دوم'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analizedepth',
            name='broker',
            field=models.CharField(default='coinex', help_text='نام صرافی یا بروکر', max_length=100, verbose_name='کارگزار'),
        ),
        migrations.AlterField(
            model_name='analizedepth',
            name='buy_price',
            field=models.FloatField(verbose_name='قیمت خرید'),
        ),
        migrations.AlterField(
            model_name='analizedepth',
            name='buy_stop_loss',
            field=models.FloatField(verbose_name='حد ضرر خرید'),
        ),
        migrations.AlterField(
            model_name='analizedepth',
            name='buy_target',
            field=models.FloatField(verbose_name='تارگت اصلی خرید'),
        ),
        migrations.AlterField(
            model_name='analizedepth',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='analizedepth',
            name='fee',
            field=models.FloatField(help_text='کارمزد کل معامله به درصد', verbose_name='کارمزد'),
        ),
        migrations.AlterField(
            model_name='analizedepth',
            name='last_price',
            field=models.FloatField(verbose_name='آخرین قیمت'),
        ),
        migrations.AlterField(
            model_name='analizedepth',
            name='market',
            field=models.CharField(help_text='مثلاً BTC/USDT', max_length=100, verbose_name='مارکت'),
        ),
        migrations.AlterField(
            model_name='analizedepth',
            name='min_buy_target',
            field=models.FloatField(verbose_name='حداقل تارگت خرید'),
        ),
        migrations.AlterField(
            model_name='analizedepth',
            name='min_sell_target',
            field=models.FloatField(verbose_name='حداقل تارگت فروش'),
        ),
        migrations.AlterField(
            model_name='analizedepth',
            name='open_buy',
            field=models.BooleanField(verbose_name='سیگنال خرید فعال؟'),
        ),
        migrations.AlterField(
            model_name='analizedepth',
            name='open_sell',
            field=models.BooleanField(verbose_name='سیگنال فروش فعال؟'),
        ),
        migrations.AlterField(
            model_name='analizedepth',
            name='resistance_main',
            field=models.FloatField(verbose_name='مقاومت اصلی'),
        ),
        migrations.AlterField(
            model_name='analizedepth',
            name='sell_price',
            field=models.FloatField(verbose_name='قیمت فروش'),
        ),
        migrations.AlterField(
            model_name='analizedepth',
            name='sell_stop_loss',
            field=models.FloatField(verbose_name='حد ضرر فروش'),
        ),
        migrations.AlterField(
            model_name='analizedepth',
            name='sell_target',
            field=models.FloatField(verbose_name='تارگت اصلی فروش'),
        ),
        migrations.AlterField(
            model_name='analizedepth',
            name='support_main',
            field=models.FloatField(verbose_name='حمایت اصلی'),
        ),
    ]
