# Generated by Django 5.1.6 on 2025-09-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_alter_analizedepth_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analizedepth',
            name='buy_power_cum_shock',
            field=models.FloatField(default=0, verbose_name='قدرت تجمیعی شوک خرید'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analizedepth',
            name='buy_power_shock',
            field=models.FloatField(default=0, verbose_name='قدرت شوک خرید'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analizedepth',
            name='buy_rate_profit',
            field=models.FloatField(default=0, verbose_name='نرخ سود احتمالی خرید'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analizedepth',
            name='buy_rr',
            field=models.FloatField(default=0, verbose_name='نسب سود به ریسک خرید'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analizedepth',
            name='sel_power_cum_shock',
            field=models.FloatField(default=0, verbose_name='قدرت تجمیعی شوک فروش'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analizedepth',
            name='sel_power_shock',
            field=models.FloatField(default=0, verbose_name='قدرت شوک فروش'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analizedepth',
            name='sell_rate_profit',
            field=models.FloatField(default=0, verbose_name='نرخ سود احتمالی فروش'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analizedepth',
            name='sell_rr',
            field=models.FloatField(default=0, verbose_name='نسب سود به ریسک فروش'),
            preserve_default=False,
        ),
    ]
