# Generated by Django 5.1.6 on 2025-09-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_analizedepth_buy_power_cum_shock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analizedepth',
            name='buy',
            field=models.BooleanField(default=False, verbose_name='خرید'),
        ),
        migrations.AddField(
            model_name='analizedepth',
            name='sell',
            field=models.BooleanField(default=False, verbose_name='فروش'),
        ),
    ]
