# Generated by Django 5.1.6 on 2025-09-05 19:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_analizedepth_buy_analizedepth_sell'),
    ]

    operations = [
        migrations.AddField(
            model_name='analizedepth',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
            preserve_default=False,
        ),
    ]
