# Generated by Django 5.1.6 on 2025-09-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_analizedepth_update_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker', models.CharField(default='coinex', max_length=100)),
                ('market', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('stop_loss', models.FloatField()),
                ('target', models.FloatField()),
                ('amount', models.FloatField()),
                ('side', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.CharField(max_length=100)),
                ('order_id', models.IntegerField(default=0)),
                ('fee', models.FloatField()),
                ('realized_pnl', models.FloatField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='analizedepth',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ بروزسانی'),
        ),
    ]
